export enum RESPONSE_STATUS_CODES {
    SUCCESS = 200,
    BAD_REQUEST = 400,
    INTERNAL_SERVER_ERROR = 500,
    NO_RECORD_FOUND = 404
}

export const enum GENDER_TYPES {
    MALE = 'MALE',
    FEMALE = 'FEMALE',
    OTHER = 'OTHER'
}

export const enum USER_ROLES_ENUM {
    SUPER = 'SUPER_ROLE',
    ADMIN = 'ADMIN_ROLE',
    USER = 'USER_ROLE'
}

export enum PERFORAMNCE_DATA_ENUM {
    EXCELLENT = 'EXCELLENT',
    SATISFACTORY = 'SATISFACTORY',
    GOOD = 'GOOD',
    UNSATISFACTORY = 'UNSATISFACTORY'
}

export const  MONGOOSE_GENDER_TYPES =  [GENDER_TYPES.MALE, GENDER_TYPES.FEMALE, GENDER_TYPES.OTHER];
export const USER_ROLES = [USER_ROLES_ENUM.SUPER, USER_ROLES_ENUM.ADMIN, USER_ROLES_ENUM.USER]
export const BCRYPT_SALT_ROUNDS  = 12;